modLoader = "javafml"
loaderVersion = "[1,)"
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "flexium"
version = "1.0.0"
displayName = "Flexium"
logoFile = "flexium-icon.png"
authors = "Flexium Team"
description = '''
Flexium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

[modproperties.flexium]
"fabric-renderer-api-v1:contains_renderer" = true
"fabric:provides" = ["indium"]

[[mixins]]
config = "flexium-common.mixins.json"

[[mixins]]
config = "flexium-neoforge.mixins.json"

[[mixins]]
config = "flexium-frapi.mixins.json"
requiredMods = ["fabric_renderer_api_v1"]

[[dependencies.flexium]]
modId = "forge"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flexium]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"
