modLoader = "javafml"
loaderVersion = "[4,)"
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "flexium"

version = "${version}"
displayName = "Flexium"

logoFile = "flexium-icon.png" #optional

authors = "Flexium Team"

description = '''
Flexium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

[modproperties.flexium]
"fabric-renderer-api-v1:contains_renderer" = true
"fabric:provides" = ["indium"]

[[mixins]]
config = "flexium-common.mixins.json"

[[mixins]]
config = "flexium-neoforge.mixins.json"

[[mixins]]
config = "flexium-sirius.mixins.json"

[[mixins]]
config = "flexium-frapi.mixins.json"
requiredMods = ["fabric_renderer_api_v1"]

[[dependencies.flexium]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.10-beta,)"
ordering = "NONE"
side = "BOTH"
